replicas: 3
celeryReplicas: 3
username: {{helmbroker.username}}
password: {{helmbroker.password}}

persistence:
  size: 10Gi
  storageClass: drycc-storage

repositories:
- name: drycc-helm-broker
  url: https://drycc-mirrors.drycc.cc/drycc-addons/addons/releases/download/latest/index.yaml

global:
  email: {{global.email}}
  gatewayClass: {{global.gatewayClass}}
  clusterDomain: {{global.clusterDomain}}
  platformDomain: {{global.helmbrokerDomain}}
  certManagerEnabled: {{global.certManagerEnabled}}