replicas: 3
celeryReplicas: 3
username: {{helmbroker.username}}
password: {{helmbroker.password}}

persistence:
  size: 10Gi
  storageClass: longhorn

repositories:
- name: drycc-helm-broker
  url: https://drycc-mirrors.drycc.cc/drycc-addons/addons/releases/download/latest/index.yaml

valkey:
  replicas: 3
  imageRegistry: registry.drycc.cc
  persistence:
    enabled: true
    size: 8Gi
    storageClass: topolvm-ssd

gateway:
  gatewayClass: {{gateway.gatewayClass}}

global:
  email: {{global.email}}
  clusterDomain: {{global.clusterDomain}}
  platformDomain: {{global.helmbrokerDomain}}
  certManagerEnabled: {{global.certManagerEnabled}}