scheduler:
  enabled: false

lvmd:
  deviceClasses:
  - name: ssd
    volume-group: lvmvg-ssd
    default: true
    spare-gb: 10

webhook:
  podMutatingWebhook:
    enabled: false
  pvcMutatingWebhook:
    enabled: false

controller:
  replicaCount: 3
  podDisruptionBudget:
    enabled: false

podSecurityPolicy:
  create: false

priorityClass:
  enabled: true

storageClasses:
  - name: topolvm-ssd
    storageClass:
      fsType: ext4
      reclaimPolicy:
      annotations: {}
      isDefaultClass: false
      volumeBindingMode: WaitForFirstConsumer
      allowVolumeExpansion: true
      additionalParameters:
        "topolvm.io/device-class": "ssd"

cert-manager:
  enabled: false